---
# VMware settings
vcenter_datacenter: "Orl-Lab-DC"
vcenter_folder: "Carlos De La Paz"
vcenter_validate_certs: false
vcenter_hostname: orl-vcenter6.presidiolab.local
vcenter_username: cdelapaz
# vcenter_password: from VMware credential

# Satellite settings
satellite_url: https://satellite.qjdst.sandbox2843.opentlc.com
# satellite_org_id: from Red Hat Satellite credential
# satellite_activation_key: from survey or inventory


# Xymon settings (optional)
xymon_server: "xymon.example.com"

# Upgrade settings
target_version: "9.7"
reboot_timeout: 900
rollback_on_failure: true

# Disk requirements
disk_requirements:
  "/": 3
  "/var": 3
  "/boot": 0.5