# inventory/rhel9_upgrade.yml
all:
  children:
    rhel9_servers:
      children:
        dev:
          hosts:
            10.211.55.8
      vars:
        ansible_user: ansible
        ansible_become: true