collections:
  # - name: ansible.netcommon
  # - name: ansible.utils
  # - name: ansible.controller
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"
  - name: redhat.rhel_system_roles
    # version: ">=1.23.0"
